/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f7f9fb",
        "inverse-primary": "#bec6e0",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "on-surface-variant": "#45464d",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#7c839b",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#b9c7e0",
        "on-tertiary-container": "#76859b",
        "on-primary-fixed": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "on-secondary-container": "#785a26",
        "primary-fixed": "#dae2fd",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "surface-tint": "#565e74",
        primary: "#000000",
        "surface-container-lowest": "#ffffff",
        outline: "#76777d",
        "secondary-container": "#fdd494",
        "on-secondary-fixed": "#281900",
        "on-secondary-fixed-variant": "#5d420f",
        "on-primary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        secondary: "#775925",
        tertiary: "#000000",
        "secondary-fixed-dim": "#e8c182",
        "tertiary-fixed": "#d5e3fd",
        error: "#ba1a1a",
        "primary-container": "#131b2e",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#0d1c2f",
        "primary-fixed-dim": "#bec6e0",
        background: "#f7f9fb",
        "on-tertiary-fixed": "#0d1c2f",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdeab",

        /* ---- the one new accent color: a deep signal-emerald ---- */
        accent: "#0E7C61",
        "accent-dark": "#0A5C48",
        "accent-container": "#DCF3EA",
        "on-accent": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        unit: "4px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "data-tabular": ["IBM Plex Sans"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "data-tabular": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      keyframes: {
        ticker: {
          "0%": { transform: "translate3d(0,0,0)" },
          "100%": { transform: "translate3d(-50%,0,0)" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.4", transform: "scale(1.3)" },
        },
      },
      animation: {
        ticker: "ticker 90s linear infinite",
        "fade-up": "fade-up 0.6s cubic-bezier(0.16,1,0.3,1) both",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
